# Generated by Django 4.0.4 on 2022-04-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '상품'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name_plural': '상품 옵션'},
        ),
        migrations.AlterModelOptions(
            name='productoptionvariation',
            options={'verbose_name_plural': '상품 값'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name_plural': '상품 세부품목'},
        ),
    ]
