# Generated by Django 4.0.4 on 2022-04-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productoptionvariation_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptionvariation',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productvariant'),
        ),
    ]
