# Generated by Django 4.0.4 on 2022-04-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productoptionvariation_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '유저'},
        ),
        migrations.AlterField(
            model_name='productoptionvariation',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='api.productvariant'),
        ),
    ]
